### ISSUE TITLE
Bug Expanding Resources

### ISSUE THREAD

**Issue by jjcollinge** [lawrencegripper/azbrowse#167]
Not had time to properly look into this but will do later and update.

Navigate: Sub -> Databricks -> VNET -> CheckIpAddressAvailability -> CRASH

```
AzBrowse is waiting for access to '~/.azbrowse.db', do you have another instance of azbrowse open?
Loading db complete
2019/11/19 14:56:15 Current version is the latest
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x886fa2]

goroutine 1 [running]:
github.com/lawrencegripper/azbrowse/pkg/armclient.(*Client).DoRequestWithBody(0x0, 0x1518280, 0xc00058c480, 0xec8afd, 0x3, 0xc0013760c0, 0xbd, 0x0, 0x0, 0x0, ...)
        /home/jjcollinge/code/go/src/github.com/lawrencegripper/azbrowse/pkg/armclient/armclient.go:114 +0x422
github.com/lawrencegripper/azbrowse/pkg/armclient.(*Client).DoRequest(...)
        /home/jjcollinge/code/go/src/github.com/lawrencegripper/azbrowse/pkg/armclient/armclient.go:96
github.com/lawrencegripper/azbrowse/internal/pkg/expanders.(*DefaultExpander).Expand(0x1bea278, 0x1518280, 0xc00058c480, 0xc0013ce000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/jjcollinge/code/go/src/github.com/lawrencegripper/azbrowse/internal/pkg/expanders/default.go:49 +0xb6
github.com/lawrencegripper/azbrowse/internal/pkg/expanders.ExpandItem(0x1518280, 0xc000454060, 0xc0013ce000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/jjcollinge/code/go/src/github.com/lawrencegripper/azbrowse/internal/pkg/expanders/expander.go:113 +0x10c1
github.com/lawrencegripper/azbrowse/internal/pkg/views.(*ListWidget).ExpandCurrentSelection(0xc000d39000)
        /home/jjcollinge/code/go/src/github.com/lawrencegripper/azbrowse/internal/pkg/views/list.go:221 +0x28a
github.com/lawrencegripper/azbrowse/internal/pkg/keybindings.ListExpandHandler.Fn.func1(0xc000b31cb0, 0xc000237770, 0xa, 0xc00110dd01)
        /home/jjcollinge/code/go/src/github.com/lawrencegripper/azbrowse/internal/pkg/keybindings/listhandlers.go:309 +0x2a
github.com/stuartleeks/gocui.(*Gui).execKeybindings(0xc000b31cb0, 0xc000237770, 0xc00110ddb8, 0x700000000, 0x2, 0x3)
        /home/jjcollinge/code/go/pkg/mod/github.com/stuartleeks/gocui@v0.4.1/gui.go:629 +0xc2
github.com/stuartleeks/gocui.(*Gui).onKey(0xc000b31cb0, 0xc00110ddb8, 0x2, 0x0)
        /home/jjcollinge/code/go/pkg/mod/github.com/stuartleeks/gocui@v0.4.1/gui.go:593 +0x19b
github.com/stuartleeks/gocui.(*Gui).handleEvent(...)
        /home/jjcollinge/code/go/pkg/mod/github.com/stuartleeks/gocui@v0.4.1/gui.go:413
github.com/stuartleeks/gocui.(*Gui).MainLoop(0xc000b31cb0, 0xc000454060, 0xc000b31cb0)
        /home/jjcollinge/code/go/pkg/mod/github.com/stuartleeks/gocui@v0.4.1/gui.go:373 +0x1e2
main.main()
        /home/jjcollinge/code/go/src/github.com/lawrencegripper/azbrowse/cmd/azbrowse/main.go:78 +0x231
```

**Comment by lawrencegripper** [comment]
Interestingly this look like it's being thrown when attempting to aquire the token... based on master armclient.go:114

```golang
        cliToken, err := c.aquireToken(false)
	if err != nil {
		return "", errors.New("Failed to acquire auth token: " + err.Error())
	}
```

**Comment by stuartleeks** [comment]
Just had a look at this with @lawrencegripper and hope to have a PR shortly :-)

**Comment by jjcollinge** [comment]
Might be worth fixing the typo `aquiteToken` -> `acquireToken` too
