### ISSUE TITLE
Bug: Possible issue with container repositories. 

### ISSUE THREAD

**Issue by lawrencegripper** [lawrencegripper/azbrowse#216]
This assertion in the fuzzer which has passed in the past now fails.

```
20:37 # make fuzz
GO111MODULE=on golangci-lint run
WARN [runner/nolint] Found unknown linters in //nolint directives: staticcheck azure header isn't canonical 
GO111MODULE=on go install ./cmd/azbrowse
azbrowse -fuzzer 5
2020/01/14 20:37:41 Current version is the latest
Loading db ...
Loading db complete


Sorry a crash occurred
 Error: Fuzzer Test `containerRegistry_root_assertExpandHas5Nodes` Failed: 
fuzzer.go:41: should be == 
        have: (int) 2
        want: (int) 5 


Please visit https://github.com/lawrencegripper/azbrowse/issues to raise a bug.
When raising please provide the details below in the issue. 
Note `Navigation Tree` may contain sensitive information, please review before posting.

Stack Trace: 
goroutine 58 [running]:
runtime/debug.Stack(0xf22793, 0x13, 0xc001056d20)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/lawrencegripper/azbrowse/internal/pkg/errorhandling.RecoveryWithCleanup()
	/workspaces/azbrowse/internal/pkg/errorhandling/recovery.go:82 +0x1db
panic(0xd8b740, 0xc0007a60b0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
log.Panicf(0xc0010b5980, 0x7b, 0xc0000e2930, 0x7, 0x7)
	/usr/local/go/src/log/log.go:345 +0xc0
github.com/lawrencegripper/azbrowse/internal/pkg/automation.(*ErrorReporter).Errorf(0xc0007a6070, 0xf5663e, 0x38, 0xc0000e2930, 0x7, 0x7)
	/workspaces/azbrowse/internal/pkg/automation/fuzzer.go:32 +0x109
github.com/nbio/st.Expect(0x1523a20, 0xc0007a6070, 0xd8a7c0, 0xc0010b87a8, 0xd8a7c0, 0x1505cd0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/nbio/st@v0.0.0-20140626010706-e9e8d9816f32/st.go:41 +0x22a
github.com/lawrencegripper/azbrowse/internal/pkg/automation.assertNavigationCorrect(0xc00079b880, 0xc00078de20, 0x2, 0x2)
	/workspaces/azbrowse/internal/pkg/automation/fuzzer.go:41 +0x1ab
github.com/lawrencegripper/azbrowse/internal/pkg/automation.StartAutomatedFuzzer.func3(0xc0005cb000, 0xc000946000, 0xbf7fa7d045a41342, 0x464beb447c, 0x1c16640, 0xc000916000, 0xc0002a5260, 0xc0006568c0, 0xff6018)
	/workspaces/azbrowse/internal/pkg/automation/fuzzer.go:209 +0x486
created by github.com/lawrencegripper/azbrowse/internal/pkg/automation.StartAutomatedFuzzer
	/workspaces/azbrowse/internal/pkg/automation/fuzzer.go:107 +0x14c

Navigation Tree: 
|-> /subscriptions/ca9f62a4-63c1-4f30-8c86-2ffd6406b618
| 
|--> /subscriptions/ca9f62a4-63c1-4f30-8c86-2ffd6406b618/resourceGroups/stable
| 
|---> /subscriptions/ca9f62a4-63c1-4f30-8c86-2ffd6406b618/resourceGroups/stable/providers/Microsoft.Resources/deployments
| 
|----> /subscriptions/ca9f62a4-63c1-4f30-8c86-2ffd6406b618/resourceGroups/stable/<activitylog>
| 
|-----> /subscriptions/ca9f62a4-63c1-4f30-8c86-2ffd6406b618/resourceGroups/stable/providers/Microsoft.ContainerRegistry/registries/gripdev

Retry: 
azbrowse -navigate '/subscriptions/ca9f62a4-63c1-4f30-8c86-2ffd6406b618/resourceGroups/stable/providers/Microsoft.ContainerRegistry/registries/gripdev'

Makefile:58: recipe for target 'fuzz' failed
make: *** [fuzz] Error 1
```

**Comment by lawrencegripper** [comment]
![Screenshot from 2020-01-14 20-40-00](https://user-images.githubusercontent.com/1939288/72380793-0fa89e00-370e-11ea-938e-3bf92476385c.png)

When browsing to repositories I do see an error so this feels valid.

**Comment by lawrencegripper** [comment]
Looks like AzBrowse is picking up and trying to use an API preview version which isn't yet you in westeurope

**Comment by lawrencegripper** [comment]
Fixed here by removing any APIs which contain `preview` from the mappings.
