### ISSUE TITLE
Panic when tracking delete operation with lossy internet

### ISSUE THREAD

**Issue by bart-jansen** [lawrencegripper/azbrowse#220]
Error:
```
Sorry a crash occurred
 Error: Get https://management.azure.com/subscriptions/1bc0b239-a5c1-4913-8b8c-6aab225b3669/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1LOFM6MkRDTFVTVEVSOjJEQkFSVEotV0VTVEVVUk9QRSIsImpvYkxvY2F0aW9uIjoid2VzdGV1cm9wZSJ9?api-version=2017-05-10: read tcp 172.20.10.11:55506->13.69.114.0:443: read: operation timed out 
```

Stack Trace:
```
goroutine 28 [running]:
runtime/debug.Stack(0x1b1d72c, 0x13, 0xc0012560c0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/lawrencegripper/azbrowse/internal/pkg/errorhandling.RecoveryWithCleanup()
	/home/vsts/work/1/s/internal/pkg/errorhandling/recovery.go:82 +0x1db
panic(0x1a0b700, 0xc0001e00c0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/lawrencegripper/azbrowse/internal/pkg/views.StartWatchingAsyncARMRequests.func2(0x2131600, 0xc000026068, 0xc0001e1d40)
	/home/vsts/work/1/s/internal/pkg/views/notifications_arm_async.go:115 +0x5ae
created by github.com/lawrencegripper/azbrowse/internal/pkg/views.StartWatchingAsyncARMRequests
	/home/vsts/work/1/s/internal/pkg/views/notifications_arm_async.go:91 +0xc3

Navigation Tree: 
|-> /subscriptions/1bc0b239-a5c1-4913-8b8c-6aab225b3669

Retry: 
azbrowse -navigate '/subscriptions/1bc0b239-a5c1-4913-8b8c-6aab225b3669'
```

**Comment by lawrencegripper** [comment]
Tracks back to the `panics` in this file, the fix is to move the panics to being something like 

```
				eventing.SendStatusEvent(&eventing.StatusEvent{
					Failure: true,
					Message: "Something went wrong tracking a delete operation",
				})
```

https://github.com/lawrencegripper/azbrowse/blob/376967c401be5df7d4bf11e0669820702e7be3d9/internal/pkg/views/notifications_arm_async.go#L54-L138
