### ISSUE TITLE
Self-update fails when installed in `/usr/local/bin` (ie. using the install script)

### ISSUE THREAD

**Issue by lawrencegripper** [lawrencegripper/azbrowse#50]
Workaround: Run with sudo and the update will work. 

Fix: `chmod` the `azbrowse`  and `.azbrowse.new` to allow them to self update but is this a security issue? Or just update the error to remind people to run under sudo. Or move install location..

```
10:56 $ azbrowse
AzBrowse is waiting for access to '~/.azbrowse.db', do you have another instance of azbrowse open?
Loading db complete


 UPDATE AVAILABLE 
 
 Release notes: Merge pull request #47 from lawrencegripper/dev 
 Do you want to update to: 1.0.202? (y/n): y
2019/02/20 10:58:55 Error occurred while updating binary: open /usr/local/bin/.azbrowse.new: permission denied
panic: Error occurred while updating binary: open /usr/local/bin/.azbrowse.new: permission denied


goroutine 1 [running]:
log.Panicln(0xc420553a70, 0x2, 0x2)
	/usr/local/go/src/log/log.go:340 +0xc0
main.confirmAndSelfUpdate()
	/go/src/github.com/lawrencegripper/azbrowse/selfupdate.go:45 +0x6d7
main.main()
	/go/src/github.com/lawrencegripper/azbrowse/main.go:67 +0x4f
```

**Comment by lawrencegripper** [comment]
Closing as moving away from the install script with `.deb` and hopefully brew and scroop soon.
